---
title: "Checking data format"
author: "Atsuko Tominaga"
output: html_notebook
---

- Last checked: `r format(Sys.Date(), "%d-%b-%Y")`

This notebook is to check whether data format of the current experiment is okay.

```{r packages, include = FALSE}
if (!require("data.table")) {install.packages("data.table"); require("data.table")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
```

```{r read, include = FALSE}
# read files and combine them
data_ls <- list.files("data")
combined <- lapply(data_ls, function(f){
  fread(paste("data/", f, sep = ""), sep = ",")
})
data <- do.call(rbind.data.frame, combined)
summary(data[expMode == "experiment"])
```

## Summary Stats for my data
```{r summary, echo = FALSE}
# name conditions
data$condition <- "NA"
data$technique <- "NA"
data[grepl("_t_", midFile)]$condition <- "teaching"
data[grepl("_p_", midFile)]$condition <- "performing"
data[grepl("a_", midFile)]$technique <- "articulation"
data[grepl("d_", midFile)]$technique <- "dynamics"
# check correct or incorrect
data$correct <- 0
data[condition == "teaching" & rating == "Yes"]$correct <- 1
data[condition == "performing" & rating == "No"]$correct <- 1

# summary
sum_stats <- data[expMode == "experiment", .(N = .N, Sum = sum(correct), Percent = (sum(correct)/24)*100), by = .(condition, technique, subjectNumber)]
sum_stats
```

## Plots
### 1. Teaching vs. Performing regardless of techniques
```{r plot1, echo = FALSE}
subset1 <- sum_stats[, .(N = .N, Sum = sum(Sum), SD_Sum = sd(Sum), Percent = sum(Sum)/(48*2)*100, SD_Percent = sd(Sum)/(48*2)*100), by = .(condition)]
subset1

plot1 <- ggplot(subset1, aes(x = condition, y = Percent, fill = condition)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin = Percent - SD_Percent, ymax = Percent + SD_Percent), width = .2, position = position_dodge(.9)) +
  geom_hline(yintercept = 50, linetype = "dashed") +
  labs(y = "Correct responses (%)")
plot1
```

### 2. Teaching vs. Performing for each technique
```{r plot2, echo = FALSE}
subset2 <- sum_stats[, .(N = .N, Sum = sum(Sum), SD_Sum = sd(Sum), Percent = sum(Sum)/(24*2)*100, SD_Percent = sd(Sum)/(24*2)*100), by = .(condition, technique)]
subset2

plot2 <- ggplot(subset2, aes(x = technique, y = Percent, fill = condition)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin = Percent - SD_Percent, ymax = Percent + SD_Percent), width = .2, position = position_dodge(.9)) +
  geom_hline(yintercept = 50, linetype = "dashed") +
  labs(y = "Correct responses (%)")
plot2
```
