---
title: 'Tempo Analysis: The Sound of Teaching Music 1'
output:
  html_notebook: default
editor_options: 
  chunk_output_type: inline
---

Description: This is a summary of all analyses for a tempo.

- Last checked: `r format(Sys.Date(), "%d-%b-%Y")`

# Overview
## IOIs

## Articulation

## Dynamics

```{r setup, include = FALSE}
# packages
# data manipulation
if (!require("data.table")) {install.packages("data.table"); require("data.table")}
# plot
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}

# ggplots
theme_set(theme_classic())
theme_update(text = element_text(size = 20, family = "Helvetica Neue LT Std 57 Condensed"), legend.position = "bottom")
```

```{r file, include = FALSE}
# create a list of data file names
lf_a_t <- list.files("../filtered/art_teaching", pattern = "txt")
lf_a_p <- list.files("../filtered/art_performing", pattern = "txt")
lf_d_t <- list.files("../filtered/dyn_teaching", pattern = "txt")
lf_d_p <- list.files("../filtered/dyn_performing", pattern = "txt")

# merge all data files into one
data <- data.table()
for (i in 1:length(lf_a_t)){
  data_i <- fread(file.path("../filtered/art_teaching", lf_a_t[i]), header = T, sep = ",", dec = ".")
  data_i$Instance <- i
  data <- rbind(data, data_i)
}
for (i in 1:length(lf_a_p)){
  data_i <- fread(file.path("../filtered/art_performing", lf_a_p[i]), header = T, sep = ",", dec = ".")
  data_i$Instance <- i
  data <- rbind(data, data_i)
}
for (i in 1:length(lf_d_t)){
  data_i <- fread(file.path("../filtered/dyn_teaching", lf_d_t[i]), header = T, sep = ",", dec = ".")
  data_i$Instance <- i
  data <- rbind(data, data_i)
}
for (i in 1:length(lf_d_p)){
  data_i <- fread(file.path("../filtered/dyn_performing", lf_d_p[i]), header = T, sep = ",", dec = ".")
  data_i$Instance <- i
  data <- rbind(data, data_i)
}

# define subcomponents
# For intervals
ls_legato <- list(c(1:7), c(17:23), c(42:48), c(58:64))
ls_staccato <- list(c(9:15), c(25:31), c(34:40), c(50:56))
ls_forte <- list(c(1:7), c(17:23), c(42:48), c(58:64))
ls_piano <- list(c(9:15), c(25:31), c(34:40), c(50:56))

# For each note (velocity only)
ls_legato_2 <- list(c(1:8), c(17:24), c(42:49), c(58:65))
ls_staccato_2 <- list(c(9:16), c(25:32), c(34:41), c(50:57))
ls_forte_2 <- list(c(1:8), c(17:24), c(42:49), c(58:65))
ls_piano_2 <- list(c(9:16), c(25:32), c(34:41), c(50:57))

# Define Skill Change (LtoS, FtoP)
change_1 <- c(8, 24, 49)
# Define Skill Change (StoL, PtoF)
change_2 <- c(16, 41, 57)
```

# IOIs
```{r ioi, include = FALSE}
data_onset <- data[Key_OnOff == 1]
data_offset <- data[Key_OnOff == 0]

data_onset$IOI <- diff(c(0, data_onset$TimeStamp))
dt_ioi <- data_onset[NoteNr != 17]
dt_ioi$Interval <- rep(1:66, nrow(dt_ioi)/66)

# assign Subcomponents
dt_ioi$Subcomponent <- "NA"
# Legato
for (phrase in 1:length(ls_legato)){
  for (note in 1:length(ls_legato[[phrase]])){
    dt_ioi[Skill == "articulation" & Interval == ls_legato[[phrase]][note]]$Subcomponent <- "Legato"
  }
}
# Staccato
for (phrase in 1:length(ls_staccato)){
  for (note in 1:length(ls_staccato[[phrase]])){
    dt_ioi[Skill == "articulation" & Interval == ls_staccato[[phrase]][note]]$Subcomponent <- "Staccato"
  }
}

# Forte
for (phrase in 1:length(ls_forte)){
  for (note in 1:length(ls_forte[[phrase]])){
    dt_ioi[Skill == "dynamics" & Interval == ls_forte[[phrase]][note]]$Subcomponent <- "Forte"
  }
}
# Piano
for (phrase in 1:length(ls_piano)){
  for (note in 1:length(ls_piano[[phrase]])){
    dt_ioi[Skill == "dynamics" & Interval == ls_piano[[phrase]][note]]$Subcomponent <- "Piano"
  }
}

# assign Subcomponent Change
for (number in change_1){
  dt_ioi[Skill == "articulation" & Interval == number]$Subcomponent <- "LtoS"
  dt_ioi[Skill == "dynamics" & Interval == number]$Subcomponent <- "FtoP"
}
for (number in change_2){
  dt_ioi[Skill == "articulation" & Interval == number]$Subcomponent <- "StoL"
  dt_ioi[Skill == "dynamics" & Interval == number]$Subcomponent <- "PtoF"
}

ioi <- dt_ioi[Subcomponent != "NA", .(N = .N, Mean = mean(IOI), SD = sd(IOI)), by = .(Instance, Condition, Skill)]
ioi_all <- ioi[, .(N = .N, Mean = mean(Mean), SD = sd(Mean)), by = .(Condition, Skill)]
```

```{r ioi_plot, echo = FALSE}
p_ioi <- ggplot(ioi, aes(x = Instance, y = Mean, fill = Condition)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin = Mean - SD, ymax = Mean + SD),
                width = .2, position = position_dodge(.9)) +
  geom_hline(yintercept = 188, linetype = "dashed") +
  facet_grid(Skill ~ .) +
  labs(y = "IOI (ms)", subtitle = "IOI: Each instance")
p_ioi

p_ioi_all <- ggplot(ioi_all, aes(x = Skill, y = Mean, fill = Condition)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin = Mean - SD, ymax = Mean + SD),
                width = .2, position = position_dodge(.9)) +
  geom_hline(yintercept = 188, linetype = "dashed") +
  labs(y = "IOI (ms)", subtitle = "IOI: Each instance")
p_ioi_all
```
