---
title: "Pilot Analysis (music perception study)"
author: "Atsuko Tominaga"
output: html_notebook
---

- Last checked: `r format(Sys.Date(), "%d-%b-%Y")`

- 10 participants (experimental error = 1)

```{r packages, include = FALSE}
if (!require("data.table")) {install.packages("data.table"); require("data.table")}
if (!require("ggpubr")) {install.packages("ggpubr"); require("ggpubr")}
```

```{r read, include = FALSE}
# read files and combine them
data_ls <- list.files("data")
combined <- lapply(data_ls, function(f){
  fread(paste("data/", f, sep = ""), sep = ",")
})
data <- do.call(rbind.data.frame, combined)
```

## Individual data
```{r summary, echo = FALSE}
# remove irrelevant strings
data$midFile <- gsub("./practice/", "", data$midFile)
data$midFile <- gsub("./mid/", "", data$midFile)
data$midFile <- gsub(".mid", "", data$midFile)

# name conditions
data$condition <- "NA"
data$technique <- "NA"
data[grepl("_t_", midFile)]$condition <- "teaching"
data[grepl("_p_", midFile)]$condition <- "performing"
data[grepl("a_", midFile)]$technique <- "articulation"
data[grepl("d_", midFile)]$technique <- "dynamics"
# check correct or incorrect
data$correct <- 0
data[condition == "teaching" & rating == "Yes"]$correct <- 1
data[condition == "performing" & rating == "No"]$correct <- 1

all <- data[expMode == "experiment", .(N = .N, Sum = sum(correct), Percent = (sum(correct)/.N)*100), by = .(subjectNumber, condition, technique)]
all[order(subjectNumber, condition, technique)]
```

## Accuracy
### All
```{r acc, echo = FALSE}
# individual
ind_data <- data[expMode == "experiment" & subjectNumber != 9, .(N = .N, Sum = sum(correct), Percent = (sum(correct)/.N)*100), by = .(subjectNumber)]
ind_data <- ind_data[order(subjectNumber)]

# all
subset <- ind_data[, .(N = .N, Mean = mean(Sum), SD = sd(Sum), Mean_Percent = (mean(Sum)/96)*100, SD_Percent = (sd(Sum)/96)*100)]
subset
```
### articulation
```{r acc-a, echo = FALSE}
# individual
ind_data_a <- data[expMode == "experiment" & technique == "articulation" & subjectNumber != 9, .(N = .N, Sum = sum(correct), Percent = (sum(correct)/.N)*100), by = .(subjectNumber)]
ind_data_a <- ind_data_a[order(subjectNumber)]

# all
subset_a <- ind_data_a[, .(N = .N, Mean = mean(Sum), SD = sd(Sum), Mean_Percent = (mean(Sum)/48)*100, SD_Percent = (sd(Sum)/48)*100)]
subset_a
```

### dynamics
```{r acc-d, echo = FALSE}
# individual
ind_data_d <- data[expMode == "experiment" & technique == "dynamics" & subjectNumber != 9, .(N = .N, Sum = sum(correct), Percent = (sum(correct)/.N)*100), by = .(subjectNumber)]
ind_data_d <- ind_data_d[order(subjectNumber)]

# all
subset_d <- ind_data_d[, .(N = .N, Mean = mean(Sum), SD = sd(Sum), Mean_Percent = (mean(Sum)/48)*100, SD_Percent = (sd(Sum)/48)*100)]
subset_d
```

```{r plot, echo = FALSE}
ind_data_t <- data[expMode == "experiment" & subjectNumber != 9, .(N = .N, Sum = sum(correct), Percent = (sum(correct)/.N)*100), by = .(subjectNumber, technique)]
ind_data_t <- ind_data_t[order(subjectNumber, technique)]

subset_t <- ind_data_t[, .(N = .N, Mean = mean(Sum), SD = sd(Sum), Mean_Percent = (mean(Sum)/48)*100, SD_Percent = (sd(Sum)/48)*100), by = .(technique)]
subset_t

data_box <- data.table(subjectNumber = ind_data_t$subjectNumber, articulation = ind_data_t[technique == "articulation"]$Percent, dynamics = ind_data_t[technique == "dynamics"]$Percent)
box <- ggpaired(data_box, cond1 = "articulation", cond2 = "dynamics", line.color = "gray", line.size = 0.4, ylab = "Correct %")
box
```

## 1. teaching vs. performing (altogether)
```{r plot1, echo = FALSE}
# individual
ind_data1 <- data[expMode == "experiment" & subjectNumber != 9, .(N = .N, Sum = sum(correct), Percent = (sum(correct)/.N)*100), by = .(subjectNumber, condition)]
ind_data1 <- ind_data1[order(subjectNumber, condition)]

# all
subset1 <- ind_data1[, .(N = .N, Mean = mean(Sum), SD = sd(Sum), Mean_Percent = (mean(Sum)/48)*100, SD_Percent = (sd(Sum)/48)*100), by = .(condition)]
subset1

data_box1 <- data.table(subjectNumber = ind_data1$subjectNumber, teaching = ind_data1[condition == "teaching"]$Percent, performing = ind_data1[condition == "performing"]$Percent)
box1 <- ggpaired(data_box1, cond1 = "teaching", cond2 = "performing", line.color = "gray", line.size = 0.4, ylab = "Correct %")
box1
```

## 2. teaching vs. performing (each technique)
```{r plot2, echo = FALSE}
# individual
ind_data2 <- data[expMode == "experiment" & subjectNumber != 9, .(N = .N, Sum = sum(correct), Percent = (sum(correct)/.N)*100), by = .(subjectNumber, condition, technique)]
ind_data2 <- ind_data2[order(subjectNumber, condition, technique)]

# all
subset2 <- ind_data2[, .(N = .N, Mean = mean(Sum), SD = sd(Sum), Mean_Percent = (mean(Sum)/24)*100, SD_Percent = (sd(Sum)/24)*100), by = .(condition, technique)]
subset2

data_box2 <- data.table(subjectNumber = ind_data2$subjectNumber, teaching = ind_data2[condition == "teaching"]$Percent, performing = ind_data2[condition == "performing"]$Percent, technique = ind_data2$technique)
box2 <- ggpaired(data_box2, cond1 = "teaching", cond2 = "performing", facet.by = "technique", line.color = "gray", line.size = 0.4, ylab = "Correct %")
box2
```

## 3. teaching (each item)
```{r item1, echo = FALSE}
# individual
ind_data3 <- data[expMode == "experiment" & subjectNumber != 9 & condition == "teaching", .(N = .N, Sum = sum(correct), Percent = (sum(correct)/.N)*100), by = .(subjectNumber, condition, technique, midFile)]
ind_data3 <- ind_data3[order(subjectNumber, condition, technique, midFile)]

# all
subset3 <- ind_data3[, .(N = .N, Mean = mean(Sum), SD = sd(Sum), Mean_Percent = (mean(Sum))*100, SD_Percent = (sd(Sum))*100), by = .(condition, technique, midFile)]
subset3[order(-Mean_Percent)]

bar <- ggplot(subset3, aes(x = reorder(midFile, Mean_Percent), y = Mean_Percent)) + geom_bar(stat = "identity")
bar
```

### articulation
```{r item1-a, echo = FALSE}
subset3_a <- subset3[technique == "articulation"]
subset3_a[order(-Mean_Percent)]

bar_a <- ggplot(subset3[technique == "articulation"], aes(x = reorder(midFile, Mean_Percent), y = Mean_Percent)) + geom_bar(stat = "identity")
bar_a
```

### dynamics
```{r item1-d, echo = FALSE}
subset3_b <- subset3[order(-Mean_Percent) & technique == "dynamics"]
subset3_b[order(-Mean_Percent)]

bar_d <- ggplot(subset3[technique == "dynamics"], aes(x = reorder(midFile, Mean_Percent), y = Mean_Percent)) + geom_bar(stat = "identity")
bar_d
```

## 3. performing (each item)
```{r item2, echo = FALSE}
# individual
ind_data4 <- data[expMode == "experiment" & subjectNumber != 9 & condition == "performing", .(N = .N, Sum = sum(correct), Percent = (sum(correct)/.N)*100), by = .(subjectNumber, condition, technique, midFile)]
ind_data4 <- ind_data4[order(subjectNumber, condition, technique, midFile)]

# all
subset4 <- ind_data4[, .(N = .N, Mean = mean(Sum), SD = sd(Sum), Mean_Percent = (mean(Sum))*100, SD_Percent = (sd(Sum))*100), by = .(condition, technique, midFile)]
subset4[order(-Mean_Percent)]

bar2 <- ggplot(subset4, aes(x = reorder(midFile, Mean_Percent), y = Mean_Percent)) + geom_bar(stat = "identity")
bar2
```

### articulation
```{r item2-a, echo = FALSE}
subset4_a <- subset4[technique == "articulation"]
subset4_a[order(-Mean_Percent)]

bar2_a <- ggplot(subset4[technique == "articulation"], aes(x = reorder(midFile, Mean_Percent), y = Mean_Percent)) + geom_bar(stat = "identity")
bar2_a
```

### dynamics
```{r item2-d, echo = FALSE}
subset4_d <- subset4[technique == "dynamics"]
subset4_d[order(-Mean_Percent)]

bar2_d <- ggplot(subset4[technique == "dynamics"], aes(x = reorder(midFile, Mean_Percent), y = Mean_Percent)) + geom_bar(stat = "identity")
bar2_d
```
